const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
const scoreLabel=document.getElementById('score'),healthLabel=document.getElementById('health'),timerLabel=document.getElementById('timer'),healthFill=document.getElementById('healthFill'),messageBox=document.getElementById('message');
const world={width:canvas.width,height:canvas.height,harvestTarget:8,timeLimit:75};const keys={};let animationFrame=null,lastTime=0,gameState='menu';
const player={x:100,y:100,radius:16,speed:220,health:100,invulnerable:0,pulseCooldown:0,pulseTimer:0};let drones=[],crops=[],barn={x:760,y:80,width:90,height:90},score=0,countdown=world.timeLimit;
function setupCrops(){crops=[{x:190,y:180,radius:14},{x:300,y:120,radius:14},{x:290,y:300,radius:14},{x:450,y:140,radius:14},{x:540,y:260,radius:14},{x:670,y:260,radius:14},{x:620,y:430,radius:14},{x:240,y:430,radius:14}];}
function resetGame(){player.x=100;player.y=100;player.health=100;player.invulnerable=0;player.pulseCooldown=0;player.pulseTimer=0;score=0;countdown=world.timeLimit;setupCrops();drones=[createDrone(760,430),createDrone(780,210),createDrone(610,500)];updateHud();}
function createDrone(x,y){return{x,y,radius:18,speed:95+Math.random()*40,drift:Math.random()*Math.PI*2};}
function updateHud(){scoreLabel.textContent=`${score} / ${world.harvestTarget}`;healthLabel.textContent=Math.max(0,Math.ceil(player.health));timerLabel.textContent=Math.max(0,Math.ceil(countdown));healthFill.style.width=`${Math.max(0,Math.min(100,player.health))}%`;}
function startGame(){resetGame();gameState='playing';messageBox.classList.remove('visible');lastTime=0;if(animationFrame)cancelAnimationFrame(animationFrame);animationFrame=requestAnimationFrame(gameLoop);}
function endGame(win){if(gameState!=='playing')return;gameState=win?'win':'lose';if(animationFrame)cancelAnimationFrame(animationFrame);messageBox.classList.add('visible');messageBox.innerHTML=`<div class="panel-content"><p class="eyebrow">Status</p><h1>${win?'Farm Reclaimed':'The Farm Was Lost'}</h1><p>${win?'You gathered the harvest and reached the barn in time.':'The replacement drones overwhelmed the field. Try another run.'}</p><p>Final score: ${score} / ${world.harvestTarget}</p><button id="startButton">Play Again</button></div>`;document.getElementById('startButton').addEventListener('click',startGame);}
function triggerPulse(){if(player.pulseCooldown>0||gameState!=='playing')return;player.pulseCooldown=2.8;player.pulseTimer=.6;spawnAlert('Pulse burst!');for(const drone of drones){const dx=drone.x-player.x,dy=drone.y-player.y,distance=Math.hypot(dx,dy)||1;if(distance<190){drone.x+=(dx/distance)*90;drone.y+=(dy/distance)*90;}}}
function handleInput(dt){let dx=0,dy=0;if(keys.w||keys.arrowup)dy-=1;if(keys.s||keys.arrowdown)dy+=1;if(keys.a||keys.arrowleft)dx-=1;if(keys.d||keys.arrowright)dx+=1;if(keys[' '])triggerPulse();if(dx||dy){const length=Math.hypot(dx,dy)||1;player.x+=dx/length*player.speed*dt;player.y+=dy/length*player.speed*dt;}player.x=Math.max(player.radius,Math.min(world.width-player.radius,player.x));player.y=Math.max(player.radius,Math.min(world.height-player.radius,player.y));}
function handleCropCollection(){for(let i=crops.length-1;i>=0;i--){const crop=crops[i];if(Math.hypot(player.x-crop.x,player.y-crop.y)<player.radius+crop.radius){crops.splice(i,1);score++;if(score>=world.harvestTarget)spawnAlert('Barn is open! Run to the barn!');}}}
function spawnAlert(message){const prev=document.getElementById('alertText');if(prev)prev.remove();const div=document.createElement('div');div.id='alertText';div.textContent=message;Object.assign(div.style,{position:'absolute',left:'50%',top:'18px',transform:'translateX(-50%)',padding:'8px 14px',background:'rgba(19,33,26,.9)',border:'1px solid rgba(202,238,177,.45)',borderRadius:'999px',color:'#ebf9d4',zIndex:'3',fontWeight:'700',letterSpacing:'.03em'});document.querySelector('.game-shell').appendChild(div);setTimeout(()=>div.remove(),1700);}
function updateDrones(dt){const difficultyBoost=1+(world.timeLimit-countdown)*.02;for(const drone of drones){const dx=player.x-drone.x,dy=player.y-drone.y,length=Math.hypot(dx,dy)||1;drone.x+=dx/length*drone.speed*difficultyBoost*dt;drone.y+=dy/length*drone.speed*difficultyBoost*dt;drone.x+=Math.sin(Date.now()*.002+drone.drift)*12*dt;drone.y+=Math.cos(Date.now()*.002+drone.drift)*12*dt;if(player.pulseTimer>0){const pd=Math.hypot(player.x-drone.x,player.y-drone.y)||1;if(pd<190){drone.x+=(drone.x-player.x)/pd*60*dt;drone.y+=(drone.y-player.y)/pd*60*dt;}}if(Math.hypot(player.x-drone.x,player.y-drone.y)<player.radius+drone.radius&&player.invulnerable<=0){player.health-=15;player.invulnerable=.7;}}for(const drone of drones){drone.x=Math.max(drone.radius,Math.min(world.width-drone.radius,drone.x));drone.y=Math.max(drone.radius,Math.min(world.height-drone.radius,drone.y));}}
function updateBarn(){const inside=player.x>barn.x&&player.x<barn.x+barn.width&&player.y>barn.y&&player.y<barn.y+barn.height;if(inside&&score>=world.harvestTarget)endGame(true);}
function update(dt){if(gameState!=='playing')return;countdown-=dt;if(countdown<=0){countdown=0;updateHud();endGame(false);return;}player.invulnerable=Math.max(0,player.invulnerable-dt);player.pulseCooldown=Math.max(0,player.pulseCooldown-dt);player.pulseTimer=Math.max(0,player.pulseTimer-dt);handleInput(dt);handleCropCollection();updateDrones(dt);updateBarn();updateHud();if(player.health<=0){player.health=0;updateHud();endGame(false);}}
function drawGround(){ctx.fillStyle='#294b32';ctx.fillRect(0,0,world.width,world.height);for(let x=0;x<world.width;x+=48)for(let y=0;y<world.height;y+=48){ctx.fillStyle=(x+y)%96===0?'#355d3d':'#2b4d35';ctx.fillRect(x,y,48,48);}ctx.fillStyle='#72532d';ctx.fillRect(0,0,world.width,26);ctx.fillRect(0,world.height-26,world.width,26);ctx.fillRect(0,0,26,world.height);ctx.fillRect(world.width-26,0,26,world.height);ctx.strokeStyle='rgba(245,242,200,.22)';ctx.lineWidth=2;for(let x=80;x<world.width-60;x+=180){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,world.height);ctx.stroke();}}
function drawCrops(){for(const crop of crops){ctx.fillStyle='#d9bb56';ctx.beginPath();ctx.arc(crop.x,crop.y,crop.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#76c964';ctx.fillRect(crop.x-5,crop.y+10,10,16);}}
function drawBarn(){ctx.fillStyle='#d2a874';ctx.fillRect(barn.x,barn.y,barn.width,barn.height);ctx.fillStyle='#9a6b3b';ctx.fillRect(barn.x+12,barn.y+18,barn.width-24,barn.height-28);ctx.fillStyle='#f4e9cf';ctx.fillRect(barn.x+32,barn.y+22,18,26);ctx.fillRect(barn.x+64,barn.y+22,18,26);ctx.fillStyle='#7d4b2b';ctx.fillRect(barn.x+42,barn.y+54,14,36);if(score>=world.harvestTarget){ctx.strokeStyle='#dff5af';ctx.lineWidth=3;ctx.strokeRect(barn.x-5,barn.y-5,barn.width+10,barn.height+10);}}
function drawPlayer(){ctx.save();if(player.invulnerable>0)ctx.globalAlpha=.6+Math.sin(Date.now()*.02)*.3;if(player.pulseTimer>0){ctx.beginPath();ctx.arc(player.x,player.y,60+player.pulseTimer*90,0,Math.PI*2);ctx.strokeStyle='rgba(141,236,255,.7)';ctx.lineWidth=3;ctx.stroke();}ctx.fillStyle='#f2d9af';ctx.beginPath();ctx.arc(player.x,player.y,player.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#3b2a20';ctx.fillRect(player.x-4,player.y-2,8,12);ctx.fillStyle='#6e3f2f';ctx.fillRect(player.x-10,player.y+12,7,12);ctx.fillRect(player.x+3,player.y+12,7,12);ctx.restore();}
function drawDrones(){for(const drone of drones){ctx.fillStyle='#dfe7f0';ctx.beginPath();ctx.arc(drone.x,drone.y,drone.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff6b6b';ctx.fillRect(drone.x-5,drone.y+12,10,6);ctx.fillRect(drone.x-3,drone.y-18,6,8);}}
function draw(){drawGround();drawBarn();drawCrops();drawDrones();drawPlayer();if(gameState==='menu'){ctx.fillStyle='rgba(0,0,0,.2)';ctx.fillRect(0,0,world.width,world.height);}}
function gameLoop(timestamp){if(!lastTime)lastTime=timestamp;const dt=Math.min((timestamp-lastTime)/1000,.033);lastTime=timestamp;update(dt);draw();if(gameState==='playing')animationFrame=requestAnimationFrame(gameLoop);}
window.addEventListener('keydown',event=>{const key=event.key.toLowerCase();keys[key]=true;if(key===' '||event.code==='Space'){event.preventDefault();keys[' ']=true;}});window.addEventListener('keyup',event=>{const key=event.key.toLowerCase();keys[key]=false;if(key===' '||event.code==='Space')keys[' ']=false;});document.getElementById('startButton').addEventListener('click',startGame);resetGame();updateHud();draw();
